[package]
name = "app-proto"
version = "0.1.0"
edition = "2024"

[dependencies]
rfd = "0.15.3"
simcore = { version = "0.1.0", path = "../simcore" }
visualize = { version = "0.1.0", path = "../visualize" }
